title: DREAMED CARS
description: Learn about cars.
permalink: ':title/'
baseurl: "/" 
url: "https://dreamedcars.github.io/" 
site-twitter: 


author: DREAMED CARS  
author-img: logo-pie.png  
about-author: This blog brings you information about the world of automotion.
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
